### PR TITLE
input()'s 'type' doesn't support 'int', but 'number'

### PR DESCRIPTION
**Pull request by biocomp**
Well, at least according to SmartThings' documentation.
And Hubitat docs are, well, lacking.

Do you know if 'int' works in Hubitat?

### CODE REVIEW

**Comment by biocomp** [comment]
Yeah, looks like in 'int' case Hubitat uses 'String' as input type, and if 'number' is used, then type is 'Long'.

**Comment by biocomp** [comment]
Also, 'polling' input is not used at all?

**Comment by Ozzymoto** [comment]
can you please help me, i get an error code with the icomfort login... im so new and lost.. i really need some help

**Comment by bspranger** [comment]
Merged conflicts

**Pull request closed without merging**
